name: Run Payment Service Tests

on:
  push:
    paths:
      - 'payment-service/**'
  pull_request:
    paths:
      - 'payment-service/**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: payment-service

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
